title: Asim's TEJ2OR Journey
description: "Showcasing my work and progress in TEJ2OR-2"
theme: minima

# Navbar Links
collections:
  navbar:
    - title: Home
      url: /
    - title: About
      url: /about
    - title: Projects
      url: /projects
      sublinks:
        - title: Night Light Project
          url: /projects/night-light
        - title: Current Project
          url: /projects/current-project
    - title: Gallery
      url: /gallery

# Other settings
paginate: 5
