title: "Asim's Project Portfolio"
description: "A showcase of my work and projects from the course"
baseurl: ""
url: "https://asim-a-dev.github.io/Asim.github.io"

theme: jekyll-theme-slate

# Navigation links
nav_links:
  - title: "Home"
    url: "/index.html"
  - title: "Gallery"
    url: "/gallery.html"
  - title: "Coursework"
    url: "/coursework.html"
  - title: "Culminating Assignment"
    url: "/culminating.html"
  - title: "Real World Project"
    url: "/real-world-project.html"
