title: "Asim Ashfaq's Course Journey"
description: "Showcasing my work, progress, and learning in the TEJ2OR-2 course"
author: "Asim Ashfaq"
theme: minima
highlighter: rouge

# Navigation menu
nav:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "Gallery"
    url: "/gallery/"
  - title: "Labs"
    url: "/labs/"
  - title: "About"
    url: "/about/"

# Enable Dropdown for Projects
projects_dropdown:
  - title: "Night Light Project"
    url: "/night-light/"
  - title: "Current Project"
    url: "/current-project/"
