title: "Asim's Course Journey"
description: "Showcasing my work throughout the course"
baseurl: ""
url: "https://asim-a-dev.github.io/Asim.github.io"

theme: minima

collections:
  projects:
    output: true
  gallery:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
