title: Your Project Name
description: A website showcasing my engineering and circuit projects.
theme: jekyll-theme-tactile

# For adding pages, like about, projects, etc.
url: "https://asim-a-dev.github.io/Asim.github.io"
baseurl: ""
exclude:
  - Gemfile
  - Gemfile.lock

# Optional: Include plugins or other settings you want.
markdown: kramdown
