title: "Asim's Course Showcase"
baseurl: ""
url: "https://asim-a-dev.github.io"   # Replace with your GitHub Pages URL
permalink: /:basename/

theme: minima  # Ensure you are using the Minima theme

# Define your navigation menu
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Projects"
    children:
      - title: "Night Light Project"
        url: "/night-light-project/"
      - title: "Current Project"
        url: "/current-project/"
  - title: "Worksheets & Labs"
    children:
      - title: "Binary Worksheet"
        url: "/binary-worksheet/"
      - title: "Logic Gates Worksheet"
        url: "/logic-gates-worksheet/"
      - title: "Labs"
        url: "/labs/"
  - title: "Gallery"
    url: "/gallery/"
