title: "Asim's TEJ2OR-2 Portfolio"
description: "A showcase of my projects and progress in the course."
theme: minima
markdown: kramdown

# Navigation bar setup
navbar:
  - name: Home
    href: /
  - name: About
    href: /about
  - name: Gallery
    href: /gallery
  - name: Projects
    dropdown:
      - name: Night Light Project
        href: /projects#night-light
      - name: Current Project
        href: /projects#current-project
