title: Asim's TEJ20R Course Overview
description: This site showcases what I've achieved in this class and how I've improved and grown as a student
theme: minima 
dark mode: true
navigation:
  - title: About
    url: /about
  - title: Gallery
    url: /gallery
  - title: Projects
    url: /projects
  - title: Culminating
    url: /culminating
  - title: Real World Project
    url: /real-world-project
