title: Asim's Real World Projects
description: A site documenting my real-world projects.
remote_theme: jekyll/minima@2.5.1


minima:
  dark_mode: true

header_pages:
  - index.md
  - about.md
  - projects.md
