title: "Asim Ashfaq - TEJ2OR-2"
description: "Showcasing My Work in TEJ2OR-2"
theme: jekyll-theme-minima
nav:
  - title: "Home"
    url: "/"
  - title: "Worksheets"
    url: "/worksheets/"
  - title: "Labs"
    url: "/labs/"
  - title: "Projects"
    dropdown:
      - title: "Night Light"
        url: "/night-light/"
      - title: "Current Project"
        url: "/current-project/"
  - title: "About"
    url: "/about/"
footer: "Asim Ashfaq - All rights reserved"
