# The theme for your website (minima is the default theme provided by GitHub Pages)
theme: "minima"

# Website settings
title: "My Course Journey"
description: "A documentation of my course progress, including projects and labs."
author: "Asim Ashfaq"

# URL and Base URL Settings
url: "https://asim-a-dev.github.io"  # Replace with your actual GitHub Pages URL
baseurl: ""  # Leave it empty since everything is in the "main" folder

# Permalink structure for your pages
permalink: /:year/:month/:day/:title/

# Social Links
social_links:
  github: "https://github.com/yourgithubprofile"  # Replace with your actual GitHub profile link

# Enable plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Markdown settings (important for .md files like current-project.md, gallery.md, etc.)
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..3

# Footer settings
footer:
  text: "Asim Ashfaq - All Rights Reserved"
  contact_email: "your_email@example.com"  # Add your contact email if needed

# Navigation settings (for the default layout)
navigation:
  - title: "Home"
    url: "/"
  - title: "Gallery"
    url: "/gallery.html"
  - title: "About"
    url: "/about.html"
  - title: "Current Project"
    url: "/current-project.md"
  - title: "Real World Project"
    url: "/real-world-project.html"
  - title: "Culminating Project"
    url: "/culminating.html"
