title: Asim's TEJ2OR Course Project
theme: minima
markdown: kramdown

# Navigation links
nav:
  - title: Home
    url: /
  - title: Coursework
    url: /coursework/
  - title: About
    url: /about/
  - title: Culminating
    url: /culminating/
  - title: Gallery
    url: /gallery/
  - title: Real World Project
    url: /real-world-project/
