title: My Project Site
description: A simple site showcasing my projects
theme: minima
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Gallery
    url: /gallery
  - title: Projects
    url: /projects
  - title: Culminating
    url: /culminating
  - title: Real World Project
    url: /real-world-project
