title: My TEJ2OR Showcase
description: A showcase of my circuit designs and experiments.
theme: jekyll-theme-tactile

url: "https://asim-a-dev.github.io/Asim.github.io"
baseurl: ""
exclude:
  - Gemfile
  - Gemfile.lock

# Optional configurations
markdown: kramdown
