# The theme for your website (Tactile is chosen for this project)
theme: jekyll-theme-tactile

# Website settings
title: "My Course Journey"
description: "A documentation of my course progress, including projects and labs."
author: "Asim Ashfaq"

# URL and Base URL Settings
url: "https://asim-a-dev.github.io"  # Replace with your actual GitHub Pages URL
baseurl: ""  # Leave it empty since everything is in the "main" folder

# Permalink structure for your pages
permalink: /:year/:month/:day/:title/

# GitHub Link (Change this to your actual GitHub profile URL if needed)
social_links:
  github: "https://github.com/yourgithubprofile"  # Replace with your actual GitHub profile link

# Enabling markdown settings (important for .md files like your project description)
markdown: kramdown
kramdown:
  input: GFM
  toc_levels: 1..3  # Control how many levels of headings to include in the table of contents

# Navigation settings (for the default layout)
navigation:
  - title: "Home"
    url: "/"
  - title: "Gallery"
    url: "/gallery.html"
  - title: "About"
    url: "/about.html"
  - title: "Current Project"
    url: "/current-project.md"
  - title: "Real World Project"
    url: "/real-world-project.html"
  - title: "Culminating Project"
    url: "/culminating.html"

# Enabling the use of plugins (useful if you need to add functionality later)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Disabling Markdown rendering in certain files (optional, if you prefer pure HTML)
markdown_ext: ".md"  # Allows .md files to be rendered properly, such as current-project.md, gallery.md, etc.

# Footer information (optional)
footer:
  text: "Asim Ashfaq - All Rights Reserved"
  contact_email: "your_email@example.com"  # Add your contact email if needed
