title: Asim's Real World Projects
description: A site documenting my real-world projects.

theme: minima

minima:
  dark_mode: false # Set this to false since we’ll use custom CSS.

plugins:
  - jekyll-remote-theme # Optional if you're using other themes/plugins


header_pages:
  - index.md
  - about.md
  - projects.md
