theme: minima
title: "Asim's Course Journey"
description: "Showcasing my work throughout the course"

# Enable navigation
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Gallery"
    url: "/gallery/"
