title: "Asim's Course Showcase"
baseurl: "" # Leave empty if this is deployed on the root of your GitHub Pages repository
url: "https://asim-a-dev.github.io" # Replace with your GitHub Pages URL

theme: minima # Using the Minima theme

# Navigation menu configuration
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Projects"
    children:
      - title: "Night Light Project"
        url: "/night-light-project/"
      - title: "Current Project"
        url: "/current-project/"
  - title: "Gallery"
    url: "/gallery/"
